include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - use_super_parameters
    - unnecessary_this
    - sort_constructors_first
